# Builds the ontology.  This Makefile is intended for out-of-source builds and
# will refuse to run if executed from the root of the source directory.  To
# build the ontoogy, create a separate build directory and run make from within
# this directory.  E.g., if the source directory is the current directory:
#
# $ mkdir build
# $ cd build
# $ make -f ../Makefile
#


#--------
# IMPORTANT: Configure the variables in this section to ensure that the
# ontology builds properly.
#--------

# Ontology terms source CSV files (REQUIRED).  These are the names of the terms
# source files that you wish to compile into the final ontology.  Note that
# these need to be specified manually because the order in which they are
# processed often matters.  As long as your project follows the suggested
# directory structure, you only need to provide the names of the files here,
# not full paths.
termsfiles := PPO_supporting_class_definitions.csv PPO_stage_definitions.csv

# The IRI (ID) for the compiled ontology (REQUIRED).
ontology_iri := 'https://raw.githubusercontent.com/PlantPhenoOntology/PPO/ontology/ppo.owl'

# The suffix to use for naming the import module OWL files generated by
# extracting terms from external ontologies (REQUIRED).
import_mod_suffix := _ppo_import_module.owl

# The location of the ontobuilder executables (OPTIONAL).  By default, the
# build process assumes that the location of the build executables has been
# added to the search path, but if that is not the case, you must provide their
# location as the value of the variable "ontobuilder_bin".
ontobuilder_bin := ../../ontobuilder/bin


#--------
# NOTE: Unless you have a non-standard source structure (i.e., you are not
# following the suggested directory structure), you should not need to modify
# anything else in the rest of this Makefile.
#--------


#--------
# Initial configuration for the build process and error checks.
#--------

# Get the location of the root of the ontology source tree.
srcroot = $(realpath $(dir $(lastword $(MAKEFILE_LIST))))

# Check if make is being run from the source directory; if so, quit.
cwd = $(realpath $(shell pwd))
ifeq ($(srcroot),$(cwd))
  $(error Error: The PPO should not be built inside the source tree.  Please \
    run make from a separate build directory)
endif

# If the location of the ontobuilder executables was not explicity provided,
# try to get it from the search path.
ifeq ($(ontobuilder_bin),)
  ontobuilder_bin := $(shell which import_module_builder.py)
endif

# Make sure we got the location of the ontobuilder executables.
ifeq ($(ontobuilder_bin),)
  $(error Error: The ontobuilder executables could not be located.  Please \
    add them to the search path or specify their location by setting the \
    the value of the variable "ontobuilder_bin" in this Makefile)
endif


#--------
# Variables and macros for processing ontology import modules.
#--------

# The location of the source files for imports.
importdir := $(srcroot)/src/imports

# Get a list of IRIs for the source ontologies from which the PPO imports.
# Note the use of "$$" to pass a single '$' to sed.
ont_IRIs := $(shell \
  tail -n +2 $(importdir)/imported_ontologies.csv | sed "s|.*,\(http://.*\)$$|\1|" \
)
#$(info $(ont_IRIs))

# A macro to generate rules for "building" (i.e., downloading) local copies of
# all of the source ontologies that the compiled ontology needs to import.  The
# macro expects a single argument, which should be the IRI of the source
# ontology.
define import_ont_rule =
$(notdir $(1)):
	wget $(1)
endef

# Generate a list of import module file names, with each module file name
# derived from the IRI of its source ontology.  E.g., if the source IRI is
# http://purl.obolibrary.org/obo/po.owl and
# import_mod_suffix == "_import_module.owl", the generated import module file
# name will be po_import_module.owl.
module_names = $(addsuffix $(import_mod_suffix), $(basename $(notdir $(ont_IRIs))))
#$(info $(module_names))


#--------
# Additional variables and macros for ontology compilation.
#--------

# The location of the ontology source files.
srcdir := $(srcroot)/src

# Generate full paths to the ontology terms source CSV files.
termsfilepaths := $(addprefix $(srcdir)/,$(termsfiles))


#--------
# Build rule definitions for the import modules.
#--------

.PHONY: imports
imports: $(module_names)

# Generate the rules for getting the source ontologies.
$(foreach IRI,$(ont_IRIs),$(eval $(call import_ont_rule,$(IRI))))
#$(foreach IRI,$(ont_IRIs),$(info $(call import_ont_rule,$(IRI))))

# A pattern rule for building import modules.  For a given import module to be
# built, both a matching CSV terms file *and* a local copy of the matching
# source ontology must be available, which means a rule for downloading the
# source ontology must be defined.
%$(import_mod_suffix): $(importdir)/%_ppo_terms.csv %.owl
	$(ontobuilder_bin)/import_module_builder.py --source $*.owl --output $@ \
	  --termsfile $(importdir)/$*_ppo_terms.csv


#--------
# Build rule definitions for the ontology.
#--------

.PHONY: ontology
ontology: ppo.owl

ppo.owl: $(srcdir)/ppo-base.owl $(termsfilepaths)
	$(ontobuilder_bin)/csv_to_owl.py -b $(srcdir)/ppo-base.owl -i $(ontology_iri) -o ppo.owl $(termsfilepaths)


# Set "ontology" as the default build goal.
.DEFAULT_GOAL := ontology

